### PR TITLE
VoFBnJwZ-fix-navigations and elements positionings

### PR DESCRIPTION
**Pull request by Code-250**
### What does this PR do?

This pull request fixes the navigations on the landing page, login page, and admin pages with their responsiveness

### Description of Task to be completed?

- should resolve all navigations as they are in figma design
- should resolve every problem that is in the codes bot positionings and any other
- should scroll to the section clicked on the navigation bar of the landing page
- add skill models on the contact page
- make responsive all admin pages and models

### How should this be manually tested?

- `git clone to have the repository to your local machine
- `git checkout fix-navigations-VoFBnJwZ` to go to the branch that you can use to test this.
- run `index.html ` in your browser
- Navigate to all different navigation links and buttons to explore how they work.
- make sure that your computer is on normal zoom which is 100%.

### Any background context you want to provide?

N/A

### What are the relevant pivotal tracker stories?

- [fix-navigatio](https://trello.com/c/VoFBnJwZ/18-fix-navigations)

### Screenshots (if appropriate)
- desktop
image

- mobile
mobile

- mobile of blogsadmin dashboard
image

- mobile of contact querries admin dashboard
image

### Questions:
N/A

### CODE REVIEW

**Review by ncutixavier — COMMENTED** [review]
Your dashboard is not responsive

**Comment by Code-250** [comment]
> Your dashboard is not responsive

the dashboard does not need to be responsive because I do not think that I will need to access the dashboard over the phone as an admin.

**Comment by ncutixavier** [comment]
Could you try to make it responsive, It's good practice and we need you to have all pages responsive

**Comment by Code-250** [comment]
No, It would take me a long time and I am in exams may next time.

**Comment by Code-250** [comment]
@ncutixavier 

I have made the dashboards responsive as you have required me to it 
Please review and let me know if there are any other stuff that I have missed

thanks.

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
